"""
Django settings for netpanzer project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_file = os.path.join(BASE_DIR, ".env")
if os.path.isfile(dotenv_file):
    dotenv.read_dotenv(dotenv_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'DEBUG' in os.environ and os.environ['DEBUG'] == 'True'
# DEBUG = True

ALLOWED_HOSTS = [
    "netpanzer.io",
    "netpanzer.com",
    "netpanzer.com.br",
    "netpanzer.info",
]

if DEBUG:
    ALLOWED_HOSTS.append("localhost")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website.apps.WebsiteConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'netpanzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'netpanzer' / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# The database must live outside the deploy directory in production. Deploys
# rsync --delete into BASE_DIR, and the database is gitignored, so anything
# kept there is destroyed on every release - which silently reset the
# announcements and would wipe all ranking and server history. NP_DB_PATH
# points somewhere the deploy does not own; the default keeps local
# development working with no configuration.
NP_DB_PATH = Path(os.environ.get('NP_DB_PATH') or (BASE_DIR / 'db.sqlite3'))

# Created here rather than in a deploy script so a fresh box, a new target or
# a local checkout all just work.
NP_DB_PATH.parent.mkdir(parents=True, exist_ok=True)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': NP_DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'netpanzer' / 'static',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Server browser / master server

# The master server speaks a backslash-delimited protocol on TCP 28900. See
# MASTERSERVER_PORT in the game's src/NetPanzer/Core/NetworkGlobals.hpp.
NP_MASTER_SERVER = os.environ.get('NP_MASTER_SERVER', 'netpanzer.io')
NP_MASTER_PORT = int(os.environ.get('NP_MASTER_PORT', '28900'))

# How long the live server list is held in memory before we re-query.
NP_LIVE_CACHE_SECONDS = int(os.environ.get('NP_LIVE_CACHE_SECONDS', '10'))

# Shared secret for the stats collection endpoint. When empty the endpoint is
# open (but still throttled), which is fine for local development.
STATS_COLLECT_TOKEN = os.environ.get('STATS_COLLECT_TOKEN', '')

# How long the per-collection ServerActivitySample rows are kept. These are
# detail rows only. The permanent history is ServerDailyStat, which is rolled
# up during ingest and never pruned, so raising or lowering this does not lose
# any long-term statistics.
NP_RAW_SAMPLE_RETENTION_DAYS = int(os.environ.get('NP_RAW_SAMPLE_RETENTION_DAYS', '30'))

# Assets survive rsync --delete, just like the production database.
NP_WEB_ROOT = Path(os.environ.get('NP_WEB_ROOT') or (NP_DB_PATH.parent / 'browser-game'))
NP_WEB_MAX_CONNECTIONS = int(os.environ.get('NP_WEB_MAX_CONNECTIONS', '64'))
NP_WEB_MAX_CONNECTIONS_PER_IP = int(os.environ.get('NP_WEB_MAX_CONNECTIONS_PER_IP', '8'))
