# Generated by Django 5.0 on 2026-08-22 02:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('address', 'port')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMonthStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('player_name', models.CharField(max_length=255)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('month', 'player_name')},
            },
        ),
        migrations.CreateModel(
            name='ServerActivitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('num_players', models.IntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.gameserver')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRoundState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('last_kills', models.IntegerField(default=0)),
                ('last_deaths', models.IntegerField(default=0)),
                ('last_score', models.IntegerField(default=0)),
                ('last_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.gameserver')),
            ],
            options={
                'unique_together': {('server', 'player_name')},
            },
        ),
    ]
