# Generated by Django 5.0 on 2026-08-22 02:45

from django.db import migrations, models
from django.db.models import F, FloatField, ExpressionWrapper


def backfill_metrics(apps, schema_editor):
    """
    Populate the stored ranking metrics for rows written before they existed.

    Expressed as an UPDATE so it does not depend on the model's recompute()
    method, which is free to change after this migration is written.
    """
    PlayerMonthStat = apps.get_model('website', 'PlayerMonthStat')
    PlayerMonthStat.objects.update(
        strength=ExpressionWrapper(
            2 * F('kills') + F('points') - 0.5 * F('deaths'),
            output_field=FloatField(),
        ),
        kd_ratio=ExpressionWrapper(
            (F('kills') + 1) * 1.0 / (F('deaths') + 1),
            output_field=FloatField(),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gameserver_playermonthstat_serveractivitysample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthstat',
            name='kd_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playermonthstat',
            name='strength',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playermonthstat',
            name='player_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        # Fill the new columns before the indexes are built over them.
        migrations.RunPython(backfill_metrics, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='playermonthstat',
            index=models.Index(fields=['month', '-strength', '-kills', 'player_name'], name='pms_month_strength_idx'),
        ),
        migrations.AddIndex(
            model_name='playermonthstat',
            index=models.Index(fields=['month', '-kills', 'deaths', 'player_name'], name='pms_month_kills_idx'),
        ),
        migrations.AddIndex(
            model_name='playermonthstat',
            index=models.Index(fields=['month', '-kd_ratio', '-kills', 'player_name'], name='pms_month_kd_idx'),
        ),
        migrations.AddIndex(
            model_name='playermonthstat',
            index=models.Index(fields=['month', '-points', '-kills', 'player_name'], name='pms_month_points_idx'),
        ),
    ]
