# Generated by Django 5.0 on 2026-08-22 03:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_history(apps, schema_editor):
    """
    Seed the permanent tables from what we already collected.

    ServerDailyStat is rolled up from the surviving raw samples, and the career
    totals are summed from the monthly archive. Both are maintained on write
    from here on, so this only has to run once.
    """
    PlayerMonthStat = apps.get_model('website', 'PlayerMonthStat')
    PlayerAllTimeStat = apps.get_model('website', 'PlayerAllTimeStat')
    ServerActivitySample = apps.get_model('website', 'ServerActivitySample')
    ServerDailyStat = apps.get_model('website', 'ServerDailyStat')

    careers = {}
    for stat in PlayerMonthStat.objects.all().iterator():
        career = careers.setdefault(stat.player_name, {
            'kills': 0, 'deaths': 0, 'score': 0, 'points': 0,
            'first_seen': stat.last_seen, 'last_seen': stat.last_seen,
        })
        career['kills'] += stat.kills
        career['deaths'] += stat.deaths
        career['score'] += stat.score
        career['points'] += stat.points
        career['first_seen'] = min(career['first_seen'], stat.last_seen)
        career['last_seen'] = max(career['last_seen'], stat.last_seen)

    PlayerAllTimeStat.objects.bulk_create([
        PlayerAllTimeStat(
            player_name=name,
            strength=2 * c['kills'] + c['points'] - 0.5 * c['deaths'],
            kd_ratio=(c['kills'] + 1) / (c['deaths'] + 1),
            **c
        )
        for name, c in careers.items()
    ], batch_size=500)

    days = {}
    for sample in ServerActivitySample.objects.all().iterator():
        key = (sample.server_id, sample.sampled_at.date())
        day = days.setdefault(key, {'peak': 0, 'total': 0, 'count': 0})
        day['peak'] = max(day['peak'], sample.num_players)
        day['total'] += sample.num_players
        day['count'] += 1

    ServerDailyStat.objects.bulk_create([
        ServerDailyStat(
            server_id=server_id,
            day=day,
            peak_players=v['peak'],
            sample_count=v['count'],
            total_players=v['total'],
            average_players=v['total'] / v['count'] if v['count'] else 0,
        )
        for (server_id, day), v in days.items()
    ], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_playermonthstat_kd_ratio_playermonthstat_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthstat',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PlayerAllTimeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('strength', models.FloatField(default=0)),
                ('kd_ratio', models.FloatField(default=0)),
                ('player_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-strength', '-kills', 'player_name'], name='pats_strength_idx'), models.Index(fields=['-kills', 'deaths', 'player_name'], name='pats_kills_idx'), models.Index(fields=['-kd_ratio', '-kills', 'player_name'], name='pats_kd_idx'), models.Index(fields=['-points', '-kills', 'player_name'], name='pats_points_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServerDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('peak_players', models.IntegerField(default=0)),
                ('sample_count', models.IntegerField(default=0)),
                ('total_players', models.IntegerField(default=0)),
                ('average_players', models.FloatField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.gameserver')),
            ],
            options={
                'indexes': [models.Index(fields=['day', '-peak_players'], name='sds_day_peak_idx')],
                'unique_together': {('server', 'day')},
            },
        ),
        migrations.RunPython(backfill_history, migrations.RunPython.noop),
    ]
